name: Build Linux Static

on:
  workflow_dispatch:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install dependencies
        run: pipx install poetry

      - name: Prepare build environment
        run: ./Telegram/build/prepare/linux.sh

      - name: Build in Docker
        run: |
          docker run --rm \
            -u $(id -u) \
            -v "$GITHUB_WORKSPACE:/usr/src/tdesktop" \
            ghcr.io/telegramdesktop/tdesktop/centos_env:latest \
            /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
            -D TDESKTOP_API_ID=2040 \
            -D TDESKTOP_API_HASH=b18441a1ff607e10a989891a5462e627

      - name: Strip binary
        run: find out -name "Telegram" -type f -executable -exec strip -s {} +

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: AyuGramDesktop-Linux
          path: out/**/Telegram
